version: '3.7'
services:
  qc_server:
    build: .
    ports:
      - "80:3838"
    volumes:
        - type: bind
          source: C:\Users\tmh331\Desktop\gits\QC4Metabolomics_test\config
          target: /config
        - type: bind
          source: C:\Users\tmh331\Desktop\gits\QC4Metabolomics_test\data
          target: /data   
    depends_on:
        - mariadb
    restart: always
    environment:
      TZ: Europe/Copenhagen

  mariadb:
    image: "mariadb"
    volumes:
      - type: bind
        source: C:\Users\tmh331\Desktop\gits\QC4Metabolomics_test\db
        target: /var/lib/mysql
    ports:
      - "12345:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_DATABASE: qc_db
      MYSQL_USER: qc_db_user
      MYSQL_PASSWORD: qc_db_pw
      TZ: Europe/Copenhagen
    command:
      'mysqld --innodb-flush-method=fsync'
      