networks:
  frontend:

services:
  mariadb:
    image: "mariadb"
    networks:
      - frontend
    volumes:
      - type: bind
        source: demo/db
        target: /var/lib/mysql
    ports:
      - "12345:3306"
    restart: always
    env_file: "settings_demo.env"
    command: 'mariadbd --skip_ssl --innodb-flush-method=fsync'
    
    
  qc_process:
    networks:
      - frontend
    image: ghcr.io/stanstrup/qc4metabolomics/qc_process:latest
    volumes:
        - type: bind
          source: demo/data
          target: /data   
    depends_on:
        - mariadb
    restart: always
    env_file: "settings_demo.env"
    command: '/setup/cron_with_env.sh'
    
    
  qc_shiny:
    networks:
      - frontend
    image: ghcr.io/stanstrup/qc4metabolomics/qc_shiny:latest
    ports:
      - "80:3838"
    volumes:
        - type: bind
          source: demo/data
          target: /data   
    depends_on:
        - mariadb
        - qc_process
    restart: always
    env_file: "settings_demo.env"
    command: '/init'


  ms_converter:
    cap_add:
      - SYS_PTRACE
    networks:
      - frontend
    image: ghcr.io/stanstrup/qc4metabolomics/qc_converter:latest
    volumes:
        - type: bind
          source: demo/data
          target: /data   
    restart: always
    env_file: "settings_demo.env"
    command: '/setup/cron_with_env.sh'


  db-backup:
    container_name: db-backup
    image: tiredofit/db-backup
    networks:
      - frontend
    volumes:
        - type: bind
          source: ./backups
          target: /backup  
    env_file: "settings_demo.env"
    depends_on:
        - mariadb
    restart: always
    