version: '3.7'

services:
  mariadb:
    image: "mariadb"
    volumes:
      - type: bind
        source: C:\Users\tmh331\Desktop\gits\QC4Metabolomics_test\db
        target: /var/lib/mysql
    ports:
      - "12345:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_DATABASE: qc_db
      MYSQL_USER: qc_db_user
      MYSQL_PASSWORD: qc_db_pw
      TZ: Europe/Copenhagen
    command: 'mysqld --innodb-flush-method=fsync'
    
    
  qc_process:
    build:
      context: .
      dockerfile: ./setup/Dockerfile
      target: process
    volumes:
        - type: bind
          source: C:\Users\tmh331\Desktop\gits\QC4Metabolomics_test\config
          target: /config
        - type: bind
          source: C:\Users\tmh331\Desktop\gits\QC4Metabolomics_test\data
          target: /data   
    depends_on:
        - mariadb
    restart: always
    environment:
      TZ: Europe/Copenhagen
    command: 'cron -f'
    
    
  qc_shiny:
    build:
      context: .
      dockerfile: ./setup/Dockerfile
      target: shiny
    ports:
      - "80:3838"
    volumes:
        - type: bind
          source: C:\Users\tmh331\Desktop\gits\QC4Metabolomics_test\config
          target: /config
        - type: bind
          source: C:\Users\tmh331\Desktop\gits\QC4Metabolomics_test\data
          target: /data   
    depends_on:
        - mariadb
    restart: always
    environment:
      TZ: Europe/Copenhagen
    command: '/usr/bin/shiny-server.sh'


  ms_converter:
    build:
      context: .
      dockerfile: ./setup/Dockerfile_converter
      target: converter
    volumes:
        - type: bind
          source: C:\Users\tmh331\Desktop\gits\QC4Metabolomics_test\data
          target: /data   
    restart: always
    environment:
      TZ: Europe/Copenhagen
      # remember to escape quotes
      msconvert_args: --filter \"scanEvent 1\" --mzML --zlib --64
      msconvert_outdir_prefix: /../mzML
    command: '/converter_scripts/converter_cron.sh'
