networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  mariadb:
    image: "mariadb"
    networks:
            frontend:
                ipv4_address: 172.20.0.2
    volumes:
      - type: bind
        source: demo\db
        target: /var/lib/mysql
    ports:
      - "12345:3306"
    restart: always
    env_file: "settings_demo.env"
    command: 'mariadbd --skip_ssl --innodb-flush-method=fsync'
    
    
  qc_process:
    networks:
            frontend:
                ipv4_address: 172.20.0.3
    build:
      context: .
      dockerfile: ./setup/Dockerfile
      target: process
    volumes:
        - type: bind
          source: demo\config
          target: /config
        - type: bind
          source: demo\data
          target: /data   
    depends_on:
        - mariadb
    restart: always
    env_file: "settings_demo.env"
    command: '/setup/cron_with_env.sh'
    
    
  qc_shiny:
    networks:
            frontend:
                ipv4_address: 172.20.0.4
    build:
      context: .
      dockerfile: ./setup/Dockerfile
      target: shiny
    ports:
      - "80:3838"
    volumes:
        - type: bind
          source: demo\config
          target: /config
        - type: bind
          source: demo\data
          target: /data   
    depends_on:
        - mariadb
        - qc_process
    restart: always
    env_file: "settings_demo.env"
    command: '/init'


  ms_converter:
    cap_add:
      - SYS_PTRACE
    networks:
            frontend:
                ipv4_address: 172.20.0.5
    build:
      context: .
      dockerfile: ./setup/Dockerfile_converter
      target: converter
    volumes:
        - type: bind
          source: demo\data
          target: /data   
    restart: always
    env_file: "settings_demo.env"
      # remember to escape quotes
    command: '/setup/cron_with_env.sh'


  db-backup:
    container_name: db-backup
    image: tiredofit/db-backup
    networks:
            frontend:
                ipv4_address: 172.20.0.6
    volumes:
      - ./backups:/backup
    env_file: "settings_demo.env"
    depends_on:
        - mariadb
    restart: always
    