FROM chambm/pwiz-skyline-i-agree-to-the-vendor-licenses AS converter


##### System libs setup #######################################################
# Install needed linux tools
RUN apt-get update -qq && \
	apt-get install -y --no-install-recommends software-properties-common dirmngr && \
	wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc && \
	add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/" && \
	apt-get update && \
    apt-get install -y --allow-unauthenticated --no-install-recommends \
	\
	r-base \
	cron \
	build-essential \
	\
	&& rm -rf /var/lib/apt
	
###############################################################################



RUN mkdir /converter_scripts
RUN mkdir /setup
COPY ./setup/converter_std.R /converter_scripts/converter_std.R
COPY ./setup/converter_std.sh /converter_scripts/converter_std.sh
COPY ./setup/cron_with_env.sh /setup/cron_with_env.sh
RUN chmod +x /setup/cron_with_env.sh
RUN chmod +x /converter_scripts/converter_std.sh

##### R packages ##########################################################

RUN echo 'options(repos=structure(c(CRAN="http://cran.r-project.org")))' > .Rprofile
RUN R -e "install.packages(c('BiocManager', 'remotes', 'purrr'))"
RUN R -e "BiocManager::install('bnosac/cronR')"
RUN R -e "library(cronR);cmd <- cron_rscript('/converter_scripts/converter_std.sh', cmd = '/bin/bash', rscript_log = '/var/log/converter_std.log');cron_add(cmd, frequency = '*/1 * * * *', id = 'Auto converter', description = 'Convert all new files every 1 minute', ask = FALSE)"

