FROM rocker/shiny:4.4.2

##### System libs setup #######################################################
# Install needed linux tools
RUN apt-get update && \
    apt-get install  -y \
	# needed for certain R packages
	libnetcdf-dev \
	libxml2-dev \
	libmysqlclient-dev \
	libssl-dev \
	\
	default-jre \
	default-jdk \
	liblzma-dev \
	libbz2-dev \
	\
	# for textshaping
	libharfbuzz-dev libfribidi-dev \
	\
	\
	librsvg2-dev \
	\
	git \
	# for easier debugging
	libgit2-dev \
	htop \
	nano \
	\
	# to read in access files (waters samples lists)
	mdbtools \
	\
	# to convert to unix line endings
	dos2unix \ 
	# igraph
	libglpk-dev \
	\
	libcurl4-openssl-dev \
  ca-certificates \
  curl \
  gnupg \
  cron \
    && update-ca-certificates \
    && rm -rf /var/lib/apt

RUN sudo R CMD javareconf
###############################################################################


##### Setup shared host folders ###############################################
RUN mkdir /config
RUN mkdir /data
###############################################################################


##### Install R packages ######################################################
# Copy rev files
# We copy only the core app without modules so that we can faster rebuild if changes are made in modules
COPY ./renv /srv/shiny-server/QC4Metabolomics/renv/
COPY ./.Rprofile renv.lock .env* /srv/shiny-server/QC4Metabolomics


# Make renv install all remaining packages
WORKDIR /srv/shiny-server/QC4Metabolomics/
RUN R -e "renv::restore()"
RUN R -e "renv::install('git2r')"

RUN R -e "BiocManager::install('bnosac/cronR')"
###############################################################################
