FROM rocker/shiny:4.4.2

##### System libs setup #######################################################
# Install needed linux tools
RUN apt-get update && \
    apt-get install  -y \
	# needed for certain R packages
	libnetcdf-dev \
	libxml2-dev \
	libmysqlclient-dev \
	libssl-dev \
	\
	default-jre \
	default-jdk \
	liblzma-dev \
	libbz2-dev \
	\
	# for textshaping
	libharfbuzz-dev libfribidi-dev \
	\
	\
	librsvg2-dev \
	\
	git \
	# for easier debugging
	libgit2-dev \
	htop \
	nano \
	\
	# to read in access files (waters samples lists)
	mdbtools \
	\
	# to convert to unix line endings
	dos2unix \ 
	# igraph
	libglpk-dev \
	\
	libcurl4-openssl-dev \
    ca-certificates \
    curl \
    gnupg \
    && update-ca-certificates \
    && rm -rf /var/lib/apt

RUN sudo R CMD javareconf
###############################################################################


##### Setup shared host folders ###############################################
RUN mkdir /config
RUN mkdir /data
###############################################################################


##### Install R packages ######################################################
# Copy rev files
# We copy only the core app without modules so that we can faster rebuild if changes are made in modules
COPY ./renv /srv/shiny-server/QC4Metabolomics/renv/
COPY ./.Rprofile renv.lock .env* /srv/shiny-server/QC4Metabolomics


# Make renv install all remaining packages
WORKDIR /srv/shiny-server/QC4Metabolomics/
RUN R -e "renv::restore()"
RUN R -e "renv::install('git2r')"

RUN R -e "BiocManager::install('bnosac/cronR')"


# Always use newest version of the package without having to do a renv snapshot
COPY ./MetabolomiQCsR /srv/shiny-server/QC4Metabolomics/MetabolomiQCsR/
RUN R -e 'install.packages("MetabolomiQCsR", repos = NULL, type = "source")'
###############################################################################


##### Copy complete Shiny App #################################################
COPY ./Modules /srv/shiny-server/QC4Metabolomics/Modules/
COPY ./setup /srv/shiny-server/QC4Metabolomics/setup/
RUN find /srv/shiny-server/QC4Metabolomics/ -type f -exec dos2unix {} +
###############################################################################


##### File permissions ########################################################
# make all app files readable (solves issue when dev in Windows, but building in Ubuntu)
# Evidently not needed and takes a lot of space
# RUN chmod -R 755 /srv/shiny-server/
###############################################################################

