name: Build and Push Docker Images

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ghcr.io/${{ github.repository_owner }}/qc4metabolomics

jobs:
  build-base:
    name: Build and Push qc_base
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push qc_base
        run: |
          docker build -f setup/Dockerfile_base -t qc_base:local -t $IMAGE_BASE/qc_base:latest .
          docker push $IMAGE_BASE/qc_base:latest

  build-process:
    name: Build and Push qc_process
    needs: build-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull qc_base from registry
        run: docker pull $IMAGE_BASE/qc_base:latest

      - name: Build and push qc_process
        run: |
          docker build -f setup/Dockerfile --target process -t qc_process:latest .
          docker tag qc_process:latest $IMAGE_BASE/qc_process:latest
          docker push $IMAGE_BASE/qc_process:latest

  build-shiny:
    name: Build and Push qc_shiny
    needs: build-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull qc_base from registry
        run: docker pull $IMAGE_BASE/qc_base:latest

      - name: Build and push qc_shiny
        run: |
          docker build -f setup/Dockerfile --target shiny -t qc_shiny:latest .
          docker tag qc_shiny:latest $IMAGE_BASE/qc_shiny:latest
          docker push $IMAGE_BASE/qc_shiny:latest
