on:
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    container: ghcr.io/stanstrup/qc4metabolomics/qc_base:latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_AUTOLOADER_ENABLED: false
      RENV_CONFIG_SYNCHRONIZED_CHECK: false
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Install pandoc and rsync
        run: apt-get update && apt-get install -y pandoc rsync

      - name: Set R library from base image
        run: |
          set -- /srv/shiny-server/QC4Metabolomics/renv/library/*/*/*/
          echo "R_LIBS=$1" >> "$GITHUB_ENV"

      - name: Install MetabolomiQCsR
        run: remotes::install_local("MetabolomiQCsR", dependencies = FALSE)
        shell: Rscript {0}

      - name: Build site
        run: pkgdown::build_site_github_pages("MetabolomiQCsR", new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          clean: false
          branch: gh-pages
          folder: MetabolomiQCsR/docs
          token: ${{ secrets.QC4METABOLOMICS_TOKEN }}
