name: Semantic Release

on:
  push:
    branches: [main, master]

jobs:
  release:
    name: Run Semantic Release
    runs-on: ubuntu-latest
    needs: [build-process, build-shiny, build-converter]
    if: success()

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install --global semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Prepare release assets
        run: |
          mkdir -p release-dist/demo/db
          mkdir -p release-dist/demo/data
          mkdir -p release-dist/backups
          cp docker-compose_demo.yml release-dist/
          cp settings_demo.env  release-dist/
          cp -r demo/data release-dist/demo

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
